name: StyleCop Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    # - name: Install StyleCop Analyzers
    #   run: Install-Package StyleCop.Analyzers

    - name: Install StyleCop
      run: dotnet add package StyleCop.Analyzers --version 1.1.118 

    - name: Build project
      run: dotnet build
