name: StyleCop Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install StyleCop Analyzers
      run: Install-Package StyleCop.Analyzers

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build

    - name: Run StyleCop
      run: dotnet build /p:ValidateStylecop=true
