name: ASP.NET 6.0 API StyleCop Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install StyleCop
      run: dotnet tool install --global StyleCop.Analyzers

    - name: Build and Analyze
      run: |
        dotnet build EnergyApi2.sln
        dotnet stylecop analyze EnergyApi2.csproj